### ISSUE TITLE
Not working with Pokemon GO

### ISSUE THREAD

**Issue by DieterHolvoet** [92lleo/StayAwake#4]
The volume up + down button combo is not working in Pokemon GO, it is working in other apps though. I'm using xposed framework version 85.1 (by romracer / 20160618).

**Comment by 92lleo** [comment]
Thanks for reporting. As it works in other apps I guess it's not the framework thats causing the problem. I'm currently having my exams, but I will look into it as soon as I can.
Could you give me your xposed log? Just open the installer app, go to logs and save them to sdcard. Thanks in advance!

**Comment by DieterHolvoet** [comment]
Your module doesn't seem to generate any log entries, I emptied the log, started Pokemon GO, failed to enable StayAwake, went into the Xposed app and succeeded to enable StayAwake with the volume buttons. Afterwards, the log section in the app still says 'Log is empty'. I also tapped the refresh button and force closed the app, still empty.

**Comment by 92lleo** [comment]
That's strange, thanks for testing. I will look into this

**Comment by asiansaga** [comment]
Confirm this, I'm on framework version 85 MIUI

**Comment by 92lleo** [comment]
Did some testing. Apparently xposed log keeps empty after clearing it which would explain your your empty log.

> 07-14 14:35:48.273 I/Xposed  ( 5681): Resume to Sense Home
> 07-14 14:35:51.808 I/Xposed  ( 5681): KeyDown detected - 24 - Sense Home
> 07-14 14:35:51.870 I/Xposed  ( 5681): KeyDown detected - 25 - Sense Home
> 07-14 14:35:51.875 I/Xposed  ( 5681): Showing Toast: [StayAwake enabled]
> 07-14 14:35:51.875 I/Xposed  ( 5681): Sense Home will stay awake
> 07-14 14:35:51.886 I/Xposed  ( 5681): KeyUp detected - 25 .. Sense Home
> 07-14 14:35:51.916 I/Xposed  ( 5681): KeyUp detected - 24 .. Sense Home
> 07-14 14:36:05.329 I/Xposed  (10465): Resume to Pokémon GO
> 07-14 14:36:18.660 I/Xposed  ( 5681): Resume to Sense Home
> 07-14 14:36:20.682 I/Xposed  ( 5681): KeyDown detected - 24 - Sense Home
> 07-14 14:36:20.842 I/Xposed  ( 5681): KeyDown detected - 25 - Sense Home
> 07-14 14:36:20.844 I/Xposed  ( 5681): Showing Toast: [StayAwake disabled]
> 07-14 14:36:20.844 I/Xposed  ( 5681): Sense Home will use default screen timeout
> 07-14 14:36:20.857 I/Xposed  ( 5681): KeyUp detected - 25 .. Sense Home
> 07-14 14:36:20.877 I/Xposed  ( 5681): KeyUp detected - 24 .. Sense Home
> 07-14 14:36:28.513 I/Xposed  (12153): Resume to Xposed Installer

(I just added the resume to logs, you won't see them)

I tested the combinations in htc sense launcher, then in pokemon go, then again in the launcher. Seems like it doesnt even get the key events from pokemon go. I'll try to figure out why and in what other ways i can hook the events or add another activation method

**Comment by 92lleo** [comment]
version 0.5.0 (commit 6d2966cb2e7abcdac2beab89b4d75bea65360f8d) adds partial support for pokémon go (and ingress) amongst other things.
I will work on a more user-friendly solution for this problem.

**Comment by QuantumRevenger** [comment]
Issue still persists with stayawake not keeping display awake while using Pokemon Go.

If I enable all apps system wide the screen stays on permanently, even when no app is open. Could you not add a whitelist / exclude the launcher?

I have CM13.0 with Xposed 86 on a Oneplus 2.

**Comment by 92lleo** [comment]
Hey @QuantumRevenger, thanks for your input. 
Since pokemon go was updated, the fix doesn't work anymore, see #7 and #6  for now.

@all
I'm sorry I could't update StayAwake as promised, but university, work, personal life (and the oktoberfest) take all of my time right now. Hopefully I'll get something done next week. I'll keep you up to date
